---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    owner: josta
    name: webapp
  name: webapp-color
  namespace: josta
data:
  color: blue
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    owner: josta
    name: webapp
  name: webapp-tls
  namespace: josta
type: secret-tls
data:
  server.crt: 
  server.key: 

# openssl req -x509 -newkey rsa:4096 -nodes -out cert.pem -keyout key.pem -days 30