---
apiVersion: # TODO
kind: ConfigMap
metadata:
  name: # TODO: Write the expected name
data:
  # TODO: Choose a color and write it in a key
---
apiVersion: v1
kind: # TODO
metadata:
  name: # TODO: Write the expected name
type: # TODO
data:
  server.crt: # TODO
  server.key: # TODO