apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    owner: josta
  name: webapp-statefulset
  namespace: josta
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  replicas: 2
  selector:
    matchLabels:
      owner: josta
      app: webapp
  serviceName: webapp-svc
  template:
    metadata:
      labels:
        owner: josta
        app: webapp
    spec:
      containers:
      - name: webapp-app
        image: akslcvhackathon1.azurecr.io/akslcvhackathon1.webapp:latest
        imagePullPolicy: Always
        args:
          - "--cert=blue"
          - "--key=/opt/tls/server.key"
          - "--cert=/opt/tls/server.cert"
        env:
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: webapp-color-configmap
              key: color
        
        livenessProbe:
          httpGet:
            path: /health
            port: webapp-port
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 120
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: webapp-port
          failureThreshold: 2
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        
        ports:
        - containerPort: 8080
          name: webapp-port
          protocol: TCP

        resources:
          limits:
            cpu: "500m"
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 300Mi

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault

        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        - mountPath: /opt/tls
          name: tls-volume
        - mountPath: /var/data
          name: data-volume

      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000

      volumes:
        - emptyDir: {}
          name: tmp-volume
        - secret:
            defaultMode: 420
            secretName: webapp-tls-secret
          name: tls-volume
        - name: data-volume
          persistentVolumeClaim:
            claimName: webapp-pvc

  updateStrategy:
    type: RollingUpdate
