apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/forwarded-for-header: X-Forwarded-For
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"

  labels:
    owner: josta
  namespace: josta
  name: webapp-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: itk5lcvhackathon.switzerlandnorth.cloudapp.azure.com
    http:
      paths:
      - backend:
          service:
            name: webapp-svc
            port:
              number: 8443
        path: /josta(/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - itk5lcvhackathon.switzerlandnorth.cloudapp.azure.com
