apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    owner: josta
  name: webapp-pvc
  namespace: josta
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20M
  storageClassName: azurefile-csi
