apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: file.csi.azure.com
    volume.kubernetes.io/storage-provisioner: file.csi.azure.com
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    owner: josta
    name: webapp 
  name: webapp-pvc
  namespace: josta
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Mb
  storageClassName: standard
