apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: true
provisioner: 
parameters:
  type: pd-standard

# Making sure that the DefaultStorageClass admission controller is enabled on the API server